name: sedge

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0 
        with:
          go-version: '1.22'
          
      - name: Download sedge sources
        run: |
          git clone https://github.com/NethermindEth/sedge.git src --branch main --single-branch
          echo "Sources downloaded."

      - name: Build sedge
        run: |
          cd src
          echo "building sedge..."
          make compile

      - name: Install sedge dependencies
        run: |
          cd src
          ls
          echo "installing sedge dependencies..."
          ./sedge deps install >> $HOME/sedge.logs

      - name: Run sedge
        run: |
          cd src
          echo "running sedge..."
          ./sedge generate --logging none -p $HOME /
          full-node --map-all --no-mev-boost --no-validator --network chiado /
          -c lighthouse:sigp/lighthouse:latest -e nethermind:nethermindeth/nethermind:master /
          --el-extra-flag Sync.NonValidatorNode=true --el-extra-flag Sync.DownloadBodiesInFastSync=false /
          --el-extra-flag Sync.DownloadReceiptsInFastSync=false /
          --cl-extra-flag checkpoint-sync-url=http://139.144.26.89:4000/

      - name: Run sedge
        run: |
          cd src
          ./sedge run -p .
